"""add fitness profile fields to users

Revision ID: f100aafacd0d
Revises: f584765b4d1b
Create Date: 2026-06-01 17:35:45.633715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f100aafacd0d'
down_revision = 'f584765b4d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=False, server_default='2000-01-01'))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False, server_default='male'))
        batch_op.add_column(sa.Column('height_cm', sa.Float(), nullable=False, server_default='170'))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=False, server_default='70'))
        batch_op.add_column(sa.Column('activity_level', sa.String(length=20), nullable=False, server_default='moderate'))
        batch_op.add_column(sa.Column('fitness_goal', sa.String(length=20), nullable=False, server_default='maintain'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth', server_default=None)
        batch_op.alter_column('gender', server_default=None)
        batch_op.alter_column('height_cm', server_default=None)
        batch_op.alter_column('weight_kg', server_default=None)
        batch_op.alter_column('activity_level', server_default=None)
        batch_op.alter_column('fitness_goal', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fitness_goal')
        batch_op.drop_column('activity_level')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('gender')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
